# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Color' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Color
  pod 'Moya', '~> 15.0'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Hashtags'
  pod 'CircleMenu'
  pod 'SimpleCheckbox'
  pod 'FloatingPanel'
  pod 'SkeletonView'
  pod 'Then'
end